server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-microservice-accounts
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"
#      - "prod"

build:
  version: "3.0"
accounts:
  message: "Accounts Service"
  contactDetails:
    email: "abc@abc.com"
    phone: "1234567890"
  onCallSupport:
    enabled: true
    phoneNumber: "1234567890"
